name: Run tests in Renode

on:
  push:
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-pip python3-yaml python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1 qemu-system-arm

      - name: Setup Zephyr
        run: |
          pip install west
          west init -l manifest
          west update

      - name: Setup Pigweed
        run: |
          source third_party/pigweed/bootstrap.sh
          pip install -r third_party/zephyr/scripts/requirements.txt

      - name: Setup Zephyr SDK
        run: |
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.4/zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          tar xvf zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          rm zephyr-sdk-0.16.4_linux-x86_64.tar.xz
          cd zephyr-sdk-0.16.4
          ./setup.sh -t all -c

      - name: Setup Renode
        run: |
          source third_party/pigweed/activate.sh
          mkdir renode-bin
          wget https://dl.antmicro.com/projects/renode/builds/renode-latest.linux-portable.tar.gz
          tar xvf renode-latest.linux-portable.tar.gz --strip-components=1 -C renode-bin
          pip install -r renode-bin/tests/requirements.txt
          echo "${PWD}/renode-bin" >> $GITHUB_PATH

      - name: Run Twister
        run: |
          source third_party/pigweed/activate.sh
          west twister -p renode_cortex_a53 -p native_sim -p qemu_cortex_a53 -A app/boards/ -x="BOARD_ROOT=." -T app/
